import { RecentlyPlayedItem, RecommendedItem, Track } from '../models';

export const MOCK_RECENTLY_PLAYED: RecentlyPlayedItem[] = [
  {
    id: 'rp1',
    title: 'Morning Coffee',
    artist: 'Various Artists',
    albumArt: 'https://picsum.photos/seed/rp1/300/300',
    type: 'playlist',
  },
  {
    id: 'rp2',
    title: 'After Hours',
    artist: 'The Weeknd',
    albumArt: 'https://picsum.photos/seed/rp2/300/300',
    type: 'album',
  },
  {
    id: 'rp3',
    title: 'Currents',
    artist: 'Tame Impala',
    albumArt: 'https://picsum.photos/seed/rp3/300/300',
    type: 'album',
  },
  {
    id: 'rp4',
    title: 'Good Kid, M.A.A.D City',
    artist: 'Kendrick Lamar',
    albumArt: 'https://picsum.photos/seed/rp4/300/300',
    type: 'album',
  },
  {
    id: 'rp5',
    title: 'Chill Hits',
    artist: 'Various Artists',
    albumArt: 'https://picsum.photos/seed/rp5/300/300',
    type: 'playlist',
  },
  {
    id: 'rp6',
    title: 'Blonde',
    artist: 'Frank Ocean',
    albumArt: 'https://picsum.photos/seed/rp6/300/300',
    type: 'album',
  },
];

export const MOCK_RECOMMENDED: RecommendedItem[] = [
  {
    id: 'rec1',
    title: 'Circles',
    artist: 'Mac Miller',
    albumArt: 'https://picsum.photos/seed/rec1/300/300',
    reason: 'Based on your recent plays',
  },
  {
    id: 'rec2',
    title: 'WHEN WE ALL FALL ASLEEP',
    artist: 'Billie Eilish',
    albumArt: 'https://picsum.photos/seed/rec2/300/300',
    reason: 'Popular with listeners like you',
  },
  {
    id: 'rec3',
    title: 'Fine Line',
    artist: 'Harry Styles',
    albumArt: 'https://picsum.photos/seed/rec3/300/300',
    reason: 'Because you liked Currents',
  },
  {
    id: 'rec4',
    title: 'Igor',
    artist: 'Tyler, the Creator',
    albumArt: 'https://picsum.photos/seed/rec4/300/300',
    reason: 'Based on your listening history',
  },
  {
    id: 'rec5',
    title: 'Positions',
    artist: 'Ariana Grande',
    albumArt: 'https://picsum.photos/seed/rec5/300/300',
    reason: 'Trending in your taste',
  },
  {
    id: 'rec6',
    title: 'Future Nostalgia',
    artist: 'Dua Lipa',
    albumArt: 'https://picsum.photos/seed/rec6/300/300',
    reason: 'Because you like pop',
  },
];

export const MOCK_TRACKS: Track[] = [
  {
    id: 'mt1',
    title: 'Electric Sunrise',
    artist: 'Nova Lights',
    album: 'Signals',
    albumArt: 'https://picsum.photos/seed/mt1/300/300',
    duration: 213000,
    genre: 'Indie Electronic',
    previewUrl: null,
    spotifyUrl: 'https://open.spotify.com',
    isLocal: true,
  },
  {
    id: 'mt2',
    title: 'Gravity Well',
    artist: 'Astral Planes',
    album: 'Outer Reaches',
    albumArt: 'https://picsum.photos/seed/mt2/300/300',
    duration: 245000,
    genre: 'Ambient',
    previewUrl: null,
    spotifyUrl: 'https://open.spotify.com',
    isLocal: true,
  },
  {
    id: 'mt3',
    title: 'Neon District',
    artist: 'Parallel City',
    album: 'Urban Echoes',
    albumArt: 'https://picsum.photos/seed/mt3/300/300',
    duration: 198000,
    genre: 'Synthwave',
    previewUrl: null,
    spotifyUrl: 'https://open.spotify.com',
    isLocal: true,
  },
  {
    id: 'mt4',
    title: 'Weightless',
    artist: 'Drift Theory',
    album: 'Float',
    albumArt: 'https://picsum.photos/seed/mt4/300/300',
    duration: 271000,
    genre: 'Chillwave',
    previewUrl: null,
    spotifyUrl: 'https://open.spotify.com',
    isLocal: true,
  },
  {
    id: 'mt5',
    title: 'Blueprint',
    artist: 'Meridian Lines',
    album: 'Architecture',
    albumArt: 'https://picsum.photos/seed/mt5/300/300',
    duration: 232000,
    genre: 'Indie Pop',
    previewUrl: null,
    spotifyUrl: 'https://open.spotify.com',
    isLocal: true,
  },
  {
    id: 'mt6',
    title: 'Solstice',
    artist: 'Golden Thread',
    album: 'Equinox',
    albumArt: 'https://picsum.photos/seed/mt6/300/300',
    duration: 187000,
    genre: 'Folk Electronic',
    previewUrl: null,
    spotifyUrl: 'https://open.spotify.com',
    isLocal: true,
  },
  {
    id: 'mt7',
    title: 'Kinetic',
    artist: 'Voltage Arc',
    album: 'Current State',
    albumArt: 'https://picsum.photos/seed/mt7/300/300',
    duration: 204000,
    genre: 'Electronic',
    previewUrl: null,
    spotifyUrl: 'https://open.spotify.com',
    isLocal: true,
  },
  {
    id: 'mt8',
    title: 'Quiet Storm',
    artist: 'Harbor Blue',
    album: 'Still Waters',
    albumArt: 'https://picsum.photos/seed/mt8/300/300',
    duration: 259000,
    genre: 'R&B',
    previewUrl: null,
    spotifyUrl: 'https://open.spotify.com',
    isLocal: true,
  },
  {
    id: 'mt9',
    title: 'Cascade',
    artist: 'Neon Moth',
    album: 'Vertigo',
    albumArt: 'https://picsum.photos/seed/mt9/300/300',
    duration: 223000,
    genre: 'Dream Pop',
    previewUrl: null,
    spotifyUrl: 'https://open.spotify.com',
    isLocal: true,
  },
  {
    id: 'mt10',
    title: 'Threshold',
    artist: 'Vapour Trail',
    album: 'Crossing',
    albumArt: 'https://picsum.photos/seed/mt10/300/300',
    duration: 241000,
    genre: 'Alternative',
    previewUrl: null,
    spotifyUrl: 'https://open.spotify.com',
    isLocal: true,
  },
];

export const MOCK_AI_PARAMS = {
  playlistTitle: 'AI Discovery Mix',
  playlistDescription: 'A carefully curated selection based on your current mood and listening intent.',
  genres: ['Indie Electronic', 'Ambient', 'Synthwave'],
  mood: 'Focused and explorative',
  tempo: 'Medium',
  artistPreferences: ['Experimental', 'Underground'],
  excludedGenres: ['Heavy Metal', 'Country'],
  searchKeywords: ['indie', 'electronic', 'chill', 'underground'],
  recommendationExplanation:
    'These tracks were selected because they match your expressed intent for exploration and your preference for electronic textures. Each artist is emerging or underrepresented, giving you the best chance of discovering something genuinely new.',
  refinementSuggestions: [
    'Try "More like this" if you want to stay in this sonic space',
    'Select "Different artists" to explore entirely new names',
    'Choose "Different genres" to shift the palette completely',
  ],
};
