/**
 * set-env.js
 *
 * Reads environment variables from the CI/CD host (Vercel, Netlify, etc.)
 * and writes them into the Angular environment files before the build runs.
 *
 * Build command on Vercel/Netlify:
 *   node set-env.js && npm run build
 *
 * Required environment variables on your hosting platform:
 *   OPENROUTER_API_KEY
 *   SPOTIFY_CLIENT_ID
 *   SPOTIFY_CLIENT_SECRET
 */

const fs = require('fs');
const path = require('path');

const envDir = path.join(__dirname, 'src', 'environments');

// Ensure target directory exists
if (!fs.existsSync(envDir)) {
  fs.mkdirSync(envDir, { recursive: true });
}

// Read from CI/CD host environment variables
const openRouterApiKey    = process.env.OPENROUTER_API_KEY    || '';
const spotifyClientId     = process.env.SPOTIFY_CLIENT_ID     || '';
const spotifyClientSecret = process.env.SPOTIFY_CLIENT_SECRET || '';

if (!openRouterApiKey)    console.warn('[set-env] Warning: OPENROUTER_API_KEY is not set — AI fallback will be used.');
if (!spotifyClientId)     console.warn('[set-env] Warning: SPOTIFY_CLIENT_ID is not set — mock catalog will be used.');
if (!spotifyClientSecret) console.warn('[set-env] Warning: SPOTIFY_CLIENT_SECRET is not set — mock catalog will be used.');

const sharedConfig = `
  openRouterApiKey: '${openRouterApiKey}',
  spotifyClientId: '${spotifyClientId}',
  spotifyClientSecret: '${spotifyClientSecret}',
  spotifyBaseUrl: 'https://api.spotify.com/v1',
  spotifyAuthUrl: 'https://accounts.spotify.com/api/token',
  appName: 'Spotify AI Discovery',
  appVersion: '1.0.0',
`;

// Production config uses proxy for OpenRouter to hide API key
const prodConfig = `// Auto-generated by set-env.js — DO NOT EDIT MANUALLY
export const environment = {
  production: true,
  openRouterBaseUrl: '/api/openai',
  openRouterModel: 'openai/gpt-4o-mini',
  spotifyRedirectUri: 'https://spotify-ai-discovery.netlify.app/', // Must match Spotify Developer Dashboard
${sharedConfig}};
`;

// Dev config connects directly (assuming local dev server)
const devConfig = `// Auto-generated by set-env.js — DO NOT EDIT MANUALLY
export const environment = {
  production: false,
  openRouterBaseUrl: 'https://openrouter.ai/api/v1',
  openRouterModel: 'openai/gpt-4o-mini',
  spotifyRedirectUri: 'http://localhost:4200/', // Local Angular default
${sharedConfig}};
`;

const prodPath = path.join(envDir, 'environment.ts');
const devPath  = path.join(envDir, 'environment.development.ts');

fs.writeFileSync(prodPath, prodConfig);
console.log(`[set-env] Written: ${prodPath}`);

// Protect local development credentials
if (!fs.existsSync(devPath)) {
  fs.writeFileSync(devPath, devConfig);
  console.log(`[set-env] Written: ${devPath}`);
} else {
  console.log(`[set-env] Skipped: ${devPath} already exists (preserving local credentials).`);
}

console.log('[set-env] Environment files generated successfully.');
